[package]
name = "rl-semaphore"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "rl-semaphore"
path = "src/main.rs"

[dependencies]
rl-semaphore-sim.workspace = true
rl-semaphore-env.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
