[package]
name = "rl-semaphore"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "rl-semaphore"
path = "src/main.rs"

[dependencies]
clap.workspace = true

[lints]
workspace = true
